name: Build and Push Docker image to Docker Hub

on: push
jobs:
  build_and_push:
    name: Build and push for multiple architectures
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, arm64]  # List of architectures
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: samuelgibhin/ngrok-discord:${{ matrix.arch }}
          build-args: |  # Pass build argument with current architecture
            ARCH=${{ matrix.arch }}
